### ISSUE TITLE
variable looks not supported

### ISSUE THREAD

**Issue by fuminori-ido-m** [gscho/dockerfile-rb#2]
Dear,

When I try to parse a Dockerfile which contains [variable](https://docs.docker.com/engine/reference/builder/) like the following:
```
ROM busybox
ENV FOO=/bar
WORKDIR ${FOO}   # WORKDIR /bar
ADD . $FOO       # ADD . /bar
COPY \$FOO /quux # COPY $FOO /quux
```

Parse failed at the 3rd line as follows:

```
Citrus::ParseError: Failed to parse input on line 3 at offset 9
WORKDIR ${FOO}   # WORKDIR /bar
         ^
```

Is it supported or not yet?

**Comment by gscho** [comment]
@fuminori-ido-m Thanks for the issue!
